# Generated by Django 5.2.14 on 2026-08-07 21:06

import anthias_server.app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anthias_app", "0007_asset_skip_ssl_verify"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "playlist_id",
                    models.TextField(
                        default=anthias_server.app.models.generate_asset_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("repeat", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("position", models.IntegerField(default=0)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "play_days",
                    models.TextField(
                        default=anthias_server.app.models._default_play_days
                    ),
                ),
                ("play_time_from", models.TimeField(blank=True, null=True)),
                ("play_time_to", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "playlists",
            },
        ),
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_items",
                        to="anthias_app.asset",
                    ),
                ),
                (
                    "child_playlist",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_item",
                        to="anthias_app.playlist",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="anthias_app.playlist",
                    ),
                ),
            ],
            options={
                "db_table": "playlist_items",
                "ordering": ["position", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("asset__isnull", False),
                                ("child_playlist__isnull", True),
                            ),
                            models.Q(
                                ("asset__isnull", True),
                                ("child_playlist__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="playlist_item_exactly_one_target",
                    )
                ],
            },
        ),
    ]
