# Generated by Django 5.2.14 on 2026-08-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anthias_app", "0007_asset_skip_ssl_verify"),
        ("anthias_app", "0007_playlist"),
    ]

    operations = []
